### ISSUE TITLE
[Bug] Builder error with typescript 4.7.4

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/builder-vite#418]
### What version of `vite` are you using?

2.9.12

### System info and storybook versions

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.8.0 - /workspace/seva-design-system/node_modules/.bin/npm
  npmPackages:
    @storybook/addon-a11y: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-vite: ^0.1.36 => 0.1.36 
    @storybook/mdx2-csf: ^0.0.3 => 0.0.3 
    @storybook/react: ^6.5.9 => 6.5.9

### Describe the Bug

After upgrading to typescript 4.7.4, I ran start-storybook and build-storybook commands and I got this error.
```cmd
info @storybook/react v6.5.9
info 
ERR! SyntaxError: /workspace/seva-design-system/.storybook/main.ts: Unexpected token, expected "from" (1:12)
ERR! 
ERR! > 1 | import type { StorybookViteConfig } from '@storybook/builder-vite';
ERR!     |             ^
ERR!   2 | import turbosnap from 'vite-plugin-turbosnap';
ERR!   3 | import svgrPlugin from 'vite-plugin-svgr';
ERR!   4 | import path from 'path';
ERR!     at instantiate (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:72:32)
ERR!     at constructor (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:358:12)
ERR!     at Parser.raise (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3335:19)
ERR!     at Parser.unexpected (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3373:16)
ERR!     at Parser.expectContextual (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3973:18)
ERR!     at Parser.parseImport (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16156:12)
ERR!     at Parser.parseStatementContent (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14643:27)
ERR!     at Parser.parseStatement (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14533:17)
ERR!     at Parser.parseBlockOrModuleBlockBody (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:15176:25)
ERR!     at Parser.parseBlockBody (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:15167:10)
ERR!     at Parser.parseProgram (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14451:10)
ERR!     at Parser.parseTopLevel (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14438:25)
ERR!     at Parser.parse (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16401:10)
ERR!     at parse (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16453:38)
ERR!     at parser (/workspace/seva-design-system/node_modules/@babel/core/lib/parser/index.js:52:34)
ERR!     at parser.next (<anonymous>)
ERR!  SyntaxError: /workspace/seva-design-system/.storybook/main.ts: Unexpected token, expected "from" (1:12)
ERR! 
ERR! > 1 | import type { StorybookViteConfig } from '@storybook/builder-vite';
ERR!     |             ^
ERR!   2 | import turbosnap from 'vite-plugin-turbosnap';
ERR!   3 | import svgrPlugin from 'vite-plugin-svgr';
ERR!   4 | import path from 'path';
ERR!     at instantiate (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:72:32)
ERR!     at constructor (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:358:12)
ERR!     at Parser.raise (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3335:19)
ERR!     at Parser.unexpected (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3373:16)
ERR!     at Parser.expectContextual (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3973:18)
ERR!     at Parser.parseImport (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16156:12)
ERR!     at Parser.parseStatementContent (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14643:27)
ERR!     at Parser.parseStatement (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14533:17)
ERR!     at Parser.parseBlockOrModuleBlockBody (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:15176:25)
ERR!     at Parser.parseBlockBody (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:15167:10)
ERR!     at Parser.parseProgram (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14451:10)
ERR!     at Parser.parseTopLevel (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14438:25)
ERR!     at Parser.parse (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16401:10)
ERR!     at parse (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16453:38)
ERR!     at parser (/workspace/seva-design-system/node_modules/@babel/core/lib/parser/index.js:52:34)
ERR!     at parser.next (<anonymous>) {
ERR!   code: 'BABEL_PARSE_ERROR',
ERR!   reasonCode: 'UnexpectedToken',
ERR!   loc: Position { line: 1, column: 12, index: 12 },
ERR!   pos: [Getter/Setter]
ERR! }
WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:72
}, descriptor)), Object.assign(new constructor(), properties));
                               ^

SyntaxError: /workspace/seva-design-system/.storybook/main.ts: Unexpected token, expected "from" (1:12)

> 1 | import type { StorybookViteConfig } from '@storybook/builder-vite';
    |             ^
  2 | import turbosnap from 'vite-plugin-turbosnap';
  3 | import svgrPlugin from 'vite-plugin-svgr';
  4 | import path from 'path';
    at instantiate (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3335:19)
    at Parser.unexpected (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3373:16)
    at Parser.expectContextual (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:3973:18)
    at Parser.parseImport (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16156:12)
    at Parser.parseStatementContent (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14643:27)
    at Parser.parseStatement (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14533:17)
    at Parser.parseBlockOrModuleBlockBody (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:15176:25)
    at Parser.parseBlockBody (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:15167:10)
    at Parser.parseProgram (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14451:10)
    at Parser.parseTopLevel (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:14438:25)
    at Parser.parse (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16401:10)
    at parse (/workspace/seva-design-system/node_modules/@babel/parser/lib/index.js:16453:38)
    at parser (/workspace/seva-design-system/node_modules/@babel/core/lib/parser/index.js:52:34)
    at parser.next (<anonymous>) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 1, column: 12, index: 12 },
  pos: [Getter/Setter]
}
error Command failed with exit code 1.
```
main.ts
```ts
import type { StorybookViteConfig } from '@storybook/builder-vite';
import turbosnap from 'vite-plugin-turbosnap';
import svgrPlugin from 'vite-plugin-svgr';
import path from 'path';
import { mergeConfig } from 'vite';

const aliasMap = {
  '@atoms': path.resolve(__dirname, '../src/components/atoms'),
  '@molecules': path.resolve(__dirname, '../src/components/molecules'),
  '@organisms': path.resolve(__dirname, '../src/components/organisms'),
  '@colors': path.resolve(__dirname, '../src/components/colors.json'),
  '@hooks': path.resolve(__dirname, '../src/components/hooks'),
  '@utils': path.resolve(__dirname, '../src/components/utils'),
  '@stories': path.resolve(__dirname, '../src/stories'),
  colors: path.resolve(__dirname, '../src/colors.scss'),
  spacing: path.resolve(__dirname, '../src/spacing.scss'),
  typography: path.resolve(__dirname, '../src/typography.scss'),
};

const config: StorybookViteConfig = {
  core: { builder: '@storybook/builder-vite' },
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-a11y', 'storybook-addon-performance'],
  staticDirs: ['../static'],
  features: { storyStoreV7: true, previewMdx2: true },
  framework: '@storybook/react',
  async viteFinal(config) {
    return mergeConfig(config, {
      base: '',
      esbuild: { jsxInject: `import 'react-loading-skeleton/dist/skeleton.css';` },
      plugins: [svgrPlugin(), { ...turbosnap({ rootDir: config.root! }), apply: 'build' }],
      css: { preprocessorOptions: { scss: { importPaths: ['src'].map((p) => path.resolve(p)) } } },
      resolve: { alias: aliasMap },
      build: {
        sourcemap: false,
        reportCompressedSize: false,
        chunkSizeWarningLimit: 1000,
        rollupOptions: {
          onwarn: (warning: { code: string }, next: (arg0: any) => void) => {
            if (warning.code === 'EVAL') return false;
            next(warning);
          },
        },
      },
    });
  },
};
export default config;
```

### Link to Minimal Reproducible Example

[Example](https://codesandbox.io/s/storybook-vite-react-ts-suz6xp?file=/package.json)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
That looks like a babel error, maybe your version of babel is not compatible with that version of typescript?

**Comment by bryanjtc** [comment]
I don’t use babel in my project, so I guessed the error is coming from one of storybook’s dependencies.

**Comment by IanVS** [comment]
Can you put together a small reproduction repo so we can take a look?  

Does this happen only at version 4.7.4 of typescript, and installing 4.7.3 works fine?

**Comment by bryanjtc** [comment]
I made a sandbox.
https://codesandbox.io/s/storybook-vite-react-ts-suz6xp

**Comment by IanVS** [comment]
Thanks, I tested out the codesandbox, and I get the same build failures with 4.6.x as well.  There are a few steps required to use typescript in storybook config files.  https://storybook.js.org/docs/react/configure/overview#configure-your-project-with-typescript

I think the easiest option is normally to install `ts-node`, but that can also cause troubles sometimes, and I can't seem to get it to work in the codesandbox.  @joshwooding do you have any tips here?  I haven't been able to use typescript for my own config files, because I have `"type": "module"` set in my package.json, and sb doesn't support ESM config files.

**Comment by shealavington** [comment]
I don't have much more to add on the topic, I get the same issue, but thought I'd share my experience.

Even if I remove the type declaration, (`StorybookViteConfig`), it complains about the following.

```
C:\mypath\.storybook\main.ts:27
export default config;
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module._compile (C:\mypath\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.newLoader [as .ts] (C:\mypath\node_modules\pirates\lib\index.js:141:7)  
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
PS C:\mypath> 
```

```
"devDeps...": {
    "@storybook/addon-actions": "^6.5.9",
    "@storybook/addon-docs": "^6.5.9",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/addon-interactions": "^6.5.9",
    "@storybook/addon-links": "^6.5.9",
    "@storybook/builder-vite": "^0.1.38",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/testing-library": "^0.0.13",
    "@storybook/vue3": "^6.5.9",
}
```

TS: v4.7.3
Node: v16.14.2

**Comment by ahnpnl** [comment]
I ran into the same error. Adding the `.babelrc` would solve the problem but it looks kinda ugly. I wish Storybook can move away from Babel somehow.

**Comment by IanVS** [comment]
Esbuild-register will be used to read configuration files in 7.0, which will greatly improve this situation.  Hopefully we will be able to start testing it out with vite builder soon, it's not quite supported just yet.

**Comment by joshwooding** [comment]
It's worth adding here, that another way of working around this issue is to use module.exports in your main file. That's the way I personally have TS working.

**Comment by bryanjtc** [comment]
I found a solution that worked for me in another issue. https://github.com/storybookjs/storybook/issues/9854#issuecomment-1198909094
If this solution for works for everyone here, then the issue should be closed

**Comment by alexanderbkl** [comment]
I had a similar error:


  Expected ")" but found "as"
  13 |  import Passwords from './components/Passwords';
  14 |  import Data from './components/Data';
  15 |  const root = ReactDOM.createRoot((document.getElementById('root') as HTMLElement));


For me this worked; create .eslintsrc.js file in root of project, and add this code:
```
module.exports = {
    extends: [
        // By extending from a plugin config, we can get recommended rules without having to add them manually.
        'eslint:recommended',
        'plugin:react/recommended',
        'plugin:import/recommended',
        'plugin:jsx-a11y/recommended',
        'plugin:@typescript-eslint/recommended',
        // This disables the formatting rules in ESLint that Prettier is going to be responsible for handling.
        // Make sure it's always the last config, so it gets the chance to override other configs.
        'eslint-config-prettier',
    ],
    settings: {
        react: {
            // Tells eslint-plugin-react to automatically detect the version of React to use.
            version: 'detect',
        },
        // Tells eslint how to resolve imports
        'import/resolver': {
            node: {
                paths: ['src'],
                extensions: ['.js', '.jsx', '.ts', '.tsx'],
            },
        },
    },
    rules: {
        // Add your own rules here to override ones from the extended configs.
    },
};
```

**Comment by bryanjtc** [comment]
Fixed in storybook v7
