### ISSUE TITLE
[Bug] Default install do not work - React TS

### ISSUE THREAD

**Issue by JesusTheHun** [storybookjs/builder-vite#474]
### What version of `vite` are you using?

3.0.4

### System info and storybook versions
```
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.8 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Edge: 103.0.1264.77
    Firefox: 100.0
    Safari: 15.6
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-vite: ^0.2.2 => 0.2.2 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```
### Describe the Bug

Following the `README.md` instructions : 

```bash
npm create vite@latest # I pick `react` then `react-ts`
npx sb init --builder @storybook/builder-vite
npm run storybook
```
 
Starting storybook leads to this : 

```
ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jonathan/IdeaProjects/storybook-builder-repro/.storybook/main.js from /Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js not supported.
ERR! main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
ERR! Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/jonathan/IdeaProjects/storybook-builder-repro/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
ERR! 
ERR!     at interopRequireDefault (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:64:16)
ERR!     at serverRequire (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:101:10)
ERR!     at getPreviewBuilder (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js:25:55)
ERR!     at buildDevStandalone (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-server/dist/cjs/build-dev.js:106:71)
ERR!     at async buildDev (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jonathan/IdeaProjects/storybook-builder-repro/.storybook/main.js from /Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js not supported.
ERR! main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
ERR! Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/jonathan/IdeaProjects/storybook-builder-repro/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
ERR! 
ERR!     at interopRequireDefault (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:64:16)
ERR!     at serverRequire (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:101:10)
ERR!     at getPreviewBuilder (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js:25:55)
ERR!     at buildDevStandalone (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-server/dist/cjs/build-dev.js:106:71)
ERR!     at async buildDev (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5) {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:64
  var result = require(filePath);
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jonathan/IdeaProjects/storybook-builder-repro/.storybook/main.js from /Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js not supported.
main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/jonathan/IdeaProjects/storybook-builder-repro/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at interopRequireDefault (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:64:16)
    at serverRequire (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:101:10)
    at getFrameworkPackage (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/presets.js:326:50)
    at loadAllPresets (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-common/dist/cjs/presets.js:356:26)
    at buildDev (/Users/jonathan/IdeaProjects/storybook-builder-repro/node_modules/@storybook/core-server/dist/cjs/build-dev.js:209:50) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Hi, there's a fix in the way that storybook creates files with `sb init`, https://github.com/storybookjs/storybook/pull/18714, that is waiting to be released.  For now, you can change the name of `.storybook/main.js` to `.storybook/main.cjs` as suggested in the error message, and you'll be back up and running.
