### ISSUE TITLE
[Bug]  TypeError: previewBuilder.bail is not a function

### ISSUE THREAD

**Issue by FezVrasta** [storybookjs/builder-vite#485]
### What version of `vite` are you using?

3.0.9

### System info and storybook versions

```
  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.1.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.1
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10 
    @storybook/addon-essentials: ^6.5.10 => 6.5.10 
    @storybook/addon-storyshots: ^6.5.10 => 6.5.10 
    @storybook/builder-vite: ^0.2.2 => 0.2.2 
    @storybook/node-logger: ^6.5.10 => 6.5.10 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.10 => 6.5.10 
```

### Describe the Bug

If I run `start-storybook`, it fails the first time, works the second, but with some errors about my Flow annotations, and works just fine the third time...

`build-storybook` always fails:

```
❯ build-storybook
info @storybook/react v6.5.10
info 
info => Cleaning outputDir: /Users/federicozivolo/Developer/frontend/storybook-static
info => Loading presets
info => Copying static files: /Users/federicozivolo/Developer/frontend/public at /Users/federicozivolo/Developer/frontend/storybook-static/
info => Compiling manager..
ERR! TypeError: previewBuilder.bail is not a function
ERR!     at /Users/federicozivolo/Developer/frontend/node_modules/@storybook/core-server/dist/cjs/build-static.js:219:26
ERR!     at async Promise.all (index 0)
ERR!     at async buildStaticStandalone (/Users/federicozivolo/Developer/frontend/node_modules/@storybook/core-server/dist/cjs/build-static.js:218:28)
ERR!     at async buildStatic (/Users/federicozivolo/Developer/frontend/node_modules/@storybook/core-server/dist/cjs/build-static.js:254:5)
ERR!  TypeError: previewBuilder.bail is not a function
ERR!     at /Users/federicozivolo/Developer/frontend/node_modules/@storybook/core-server/dist/cjs/build-static.js:219:26
ERR!     at async Promise.all (index 0)
ERR!     at async buildStaticStandalone (/Users/federicozivolo/Developer/frontend/node_modules/@storybook/core-server/dist/cjs/build-static.js:218:28)
ERR!     at async buildStatic (/Users/federicozivolo/Developer/frontend/node_modules/@storybook/core-server/dist/cjs/build-static.js:254:5)
info => Loading presets
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AnnikenYT** [comment]
Having a similar issue:
Package `vite-plugin-pages`
```js
const Pages = require('vite-plugin-pages');
module.exports = {
/* ... */
  async viteFinal(config, { configType }) {
    return mergeConfig(config, {
        plugins: [
            Pages({
            extensions: ['vue']
        })]
    });
  }
}
```
=> `ERR! TypeError: Pages is not a function`

**Comment by FezVrasta** [comment]
@AnnikenYT that seems a completely unrelated error.

**Comment by IanVS** [comment]
That's very strange, @FezVrasta.  It's definitely a function: https://github.com/storybookjs/builder-vite/blob/0affa702ec8ef7231e6274fb33a7ff27dc1d01b9/packages/builder-vite/index.ts#L60-L68

Can you share your `.storybook/main.js`?

**Comment by FezVrasta** [comment]
I tried to add a console.log right before `bail` is called and this is what I see:

```
{          
  start: [AsyncFunction: start],
  build: [AsyncFunction: build],
  corePresets: [],
  previewPresets: []
}
```

**Comment by FezVrasta** [comment]
Oh my, I'm sorry, I noticed I had a custom resolution for `"html-webpack-plugin": "^5.5.0",` because in the past there was a problem with Storybook not picking the correct one, removing it fixes the issue of course 🤦 

I think there's still a problem with that `bail` call though, but it's not an issue as long the build doesn't fail and needs to call it.

Also, now I get an out of memory error when I try to build my app :-(

```

<--- Last few GCs --->

[38226:0x158008000]    73516 ms: Mark-sweep 4026.5 (4141.2) -> 4023.6 (4140.3) MB, 1221.8 / 0.0 ms  (average mu = 0.334, current mu = 0.032) allocation failure scavenge might not succeed
[38226:0x158008000]    75659 ms: Mark-sweep 4039.3 (4140.3) -> 4038.1 (4169.0) MB, 2139.8 / 0.0 ms  (average mu = 0.141, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x102a646e8 node::Abort() [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 2: 0x102a64870 node::errors::TryCatchScope::~TryCatchScope() [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 3: 0x102bb4000 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 4: 0x102bb3f94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 5: 0x102d376ac v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 6: 0x102d361cc v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 7: 0x102d41514 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 8: 0x102d415a8 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
 9: 0x102d1443c v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
10: 0x10304c540 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
11: 0x103360bcc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
12: 0x10331d898 Builtins_ArrayPrototypePush [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
13: 0x1083d4a88 
14: 0x1088cccfc 
15: 0x109d2cac8 
16: 0x107c2e57c 
17: 0x108df6918 
18: 0x1032f4858 Builtins_InterpreterEntryTrampoline [/Users/federicozivolo/.nvm/versions/node/v16.16.0/bin/node]
19: 0x107e3b124 
```

**Comment by IanVS** [comment]
Webpack is still used for the "manager" part of storybook (the sidebar, addons panel, toolbar, etc), at least until storybook 7 is released.  

This looks like a bug in the vite-builder, but I'm not sure why we've never hit it before. 

In the meantime, I think your config will also cause some problems.  If you merge in your vite `plugins` to the storybook config, you will have duplicate react plugins.  

I saw your latest comment, glad that was the issue.  But yes, we should still fix the bail issue.

As for the memory, we find that vite requires a lot of memory to build, and storybook together with it adds even more.  You can normally use `--max-old-space-size` to increase the memory available to node while building.

**Comment by ariaBennett** [comment]
For what it's worth I'm hitting this same issue. I've been on a long chain of dependency errors starting I think with upgrading create-react-app to v5 which led to updating all sorts of things, and I'm assuming updating typescript which ran me into webpack errors. I ran the storybook terminal migration and also added an override for webpack 5.74 in my package.json and now I'm here.

**Comment by shadow7412** [comment]
@joshwooding I'm getting this issue too. Can this be released to NPM?

**Comment by joshwooding** [comment]
@shadow7412 0.2.5 has now been released 🎉
