### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by FezVrasta** [storybookjs/builder-vite#489]
### What version of `vite` are you using?

3.0.9

### System info and storybook versions

```
  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.1.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.1
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10 
    @storybook/addon-essentials: ^6.5.10 => 6.5.10 
    @storybook/addon-storyshots: ^6.5.10 => 6.5.10 
    @storybook/builder-vite: ^0.2.2 => 0.2.2 
    @storybook/node-logger: ^6.5.10 => 6.5.10 
    @storybook/react: ^6.5.10 => 6.5.10
```

### Describe the Bug

Environment variables are not being injected into `import.meta.env` on production builds (output of `build-storybook`), they are available on `start-storybook` though).

The only variables available are the ones starting with `STORYBOOK_`, but others starting with `VITE_` and the whitelisted ones such as `NODE_ENV`, `STORYBOOK` etc are all unset.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Hi, https://github.com/storybookjs/builder-vite/blob/0affa702ec8ef7231e6274fb33a7ff27dc1d01b9/packages/builder-vite/envs.ts#L47 is where we handle stringifying everything for `import.meta.env`.  

Can you share a minimal reproduction that demonstrates the issue you're seeing?

**Comment by FezVrasta** [comment]
I tried to create a repro but I'm getting a problem on the storybook prod build where Storybook renders itself instead of the sample story I provided. When ran with `start-storybook` it works as expected.

https://github.com/fezvrasta/storybook-builder-vite-issue-489

<img width="836" alt="CleanShot 2022-08-30 at 2 39 13@2x" src="https://user-images.githubusercontent.com/5382443/187438690-ff1dfd1e-6a42-445b-8f4b-8af784ed3330.png">

**Comment by limbyungki** [comment]
"vue": "^3.2.39"
"@storybook/builder-vite": "^0.2.2"

![err](https://user-images.githubusercontent.com/22608296/190035011-3e9498cb-ecb0-47aa-8aad-3903d823c9bc.PNG)

Cannot read properties of undefined (reading 'VITE_KAKAO_MAP_APP_KEY')
TypeError: Cannot read properties of undefined (reading 'VITE_KAKAO_MAP_APP_KEY')
    at http://localhost:6006/main.iframe.bundle.js:1479:89
    at callWithErrorHandling (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:32745:22)
    at callWithAsyncErrorHandling (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:32754:21)
    at hook.__weh.hook.__weh (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:35269:29)
    at flushPostFlushCbs (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:32926:47)
    at render (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:38799:9)
    at mount (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:37004:25)
    at app.mount (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:42194:23)
    at app.mount (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:103825:21)
    at PreviewWeb.renderToDOM (http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-node_modules_storybook_addon-backgrou-412778.iframe.bundle.js:25478:25)

**Comment by IanVS** [comment]
@limbyungki can you share the section of your code where this is coming from?

**Comment by limbyungki** [comment]
SgMap.vue
~
onMounted(() => {
  if (window.kakao && window.kakao.maps) {
    initMap();
  } else {
    const script = document.createElement('script');
    script.onload = () => kakao.maps.load(initMap);
    const appkey = import.meta.env.VITE_KAKAO_MAP_APP_KEY;
    script.src =
      'http://dapi.kakao.com/v2/maps/sdk.js?autoload=false&appkey=' + appkey;
    document.head.appendChild(script);
  }
});

const style = computed(() => ({
  height: props.height,
}));
</script>

<template>
  <VCard class="mx-auto" variant="outlined">
    <VCardItem>
      <div id="map" :style="style"></div>
    </VCardItem>
  </VCard>
</template>

-------------------



import {
  Title,
  Subtitle,
  Description,
  Primary,
  ArgsTable,
  Stories,
  Canvas,
  Meta,
  Story,
} from '@storybook/addon-docs';
import SgMap from '@/components/common/functional/SgMap.vue';
import Diagram from '@/components/stories/assets/SgMap.drawio.png';

<Meta
  title='Functional/SgMap'
  component={SgMap}
  parameters={{
    componentSubtitle: '지도 공통 컴포넌트',
  }}
  argTypes={{
    height: {
      name: 'height',
      description: '지도 화면 높이 지정',
      control: { type: 'string' },
    },
    latitude: {
      name: 'latitude',
      description: '지도 중앙 위도 지정',
      control: { type: 'number' },
    },
    longitude: {
      name: 'longitude',
      description: '지도 중앙 경도 지정',
      control: { type: 'number' },
    },
    level: {
      name: 'level',
      description: '지도 줌 레벨',
      control: { type: 'number' },
    },
    markers: {
      name: 'markers',
      description: '마커 표시 설정',
      control: { type: 'object' },
    },
  }}
  args={{
    height: '800px',
    latitude: 33.450701,
    longitude: 126.570667,
    level: 4,
    markers: [
      {
        title: '카카오',
        latitude: 33.450705,
        longitude: 126.570677,
        marker: 'marker',
        content: '<div style="padding:5px;">Hello World 1</div>',
      },
      {
        title: '생태연못',
        latitude: 33.450936,
        longitude: 126.569477,
        marker: 'markerRed',
        content: '<div style="padding:5px;">Hello World 2</div>',
      },
      {
        title: '텃밭',
        latitude: 33.450879,
        longitude: 126.56994,
        marker: 'markerStar',
        content: '<div style="padding:5px;">Hello World 3</div>',
      },
      {
        title: '근린공원',
        latitude: 33.451393,
        longitude: 126.570738,
        marker: 'markerRed',
        content: '<div style="padding:5px;">Hello World 4</div>',
      },
    ],
  }}
/>

export const Template = (args) => ({
  components: { SgMap },
  setup() {
    return { args };
  },
  template: '<SgMap v-bind="args" />',
});

<Title />
<Subtitle />
<Description />

**Comment by IanVS** [comment]
Thanks.  Do you have any kind of `envPrefix` set in your `viteFinal`, by chance?  https://vitejs.dev/config/shared-options.html#envprefix

**Comment by limbyungki** [comment]
vite.config.js

import path from 'path';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vuetify from 'vite-plugin-vuetify';
import vueI18n from '@intlify/vite-plugin-vue-i18n';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    vue(),
    vueI18n({
      include: path.resolve(__dirname, './src/locales/**'),
    }),
    VitePWA(),
    vuetify({ autoImport: true }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
      'vue-i18n': 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js',
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: 'vuetify.config.js',
    deps: {
      inline: ['vuetify'],
    },
  },
  server: {
    port: '3000',
  },
});

------------

.storybook/main.js

const path = require('path');
const { mergeConfig } = require('vite');
const vuetify = require('vite-plugin-vuetify');

module.exports = {
  stories: [
    '../src/**/Intro.stories.mdx',
    '../src/components/stories/ui/*.stories.mdx',
    '../src/components/stories/functional/*.stories.mdx',
    '../src/components/stories/app/*.stories.mdx',
    '../src/**/*.stories.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    'storybook-addon-vuetify3',
  ],
  framework: '@storybook/vue3',
  core: {
    builder: '@storybook/builder-vite',
    //builder: '@storybook/builder-webpack5',
  },
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
    });
    return config;
  },
  async viteFinal(config, { configType }) {
    config.resolve.alias['~storybook'] = path.resolve(__dirname);
    config.resolve.alias['@'] = path.resolve(__dirname, '..', 'src');
    config.plugins = [
      ...config.plugins,
      vuetify({
        autoImport: true,
      }),
    ];
    return mergeConfig(config, {
      // customize the Vite config here
      resolve: {
        alias: {
          '@': path.resolve(__dirname, 'src'),
        },
      },
    });
  },
  features: {
    storyStoreV7: true,
  },
};

----------------

.storybook/preview.js

import { withVuetify } from 'storybook-addon-vuetify3/dist/decorators';
import { app } from '@storybook/vue3';
import SgButton from '@/components/common/ui/SgButton.vue';
import SgRadio from '@/components/common/ui/SgRadio.vue';
import SgTitle from '@/components/common/ui/SgTitle.vue';
import SgLabel from '@/components/common/ui/SgLabel.vue';
import SgMap from '@/components/common/functional/SgMap.vue';
import SgImageViewer from '@/components/common/functional/SgImageViewer.vue';
import SgCheckbox from '@/components/common/ui/SgCheckbox.vue';

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    expanded: true,
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

export const decorators = [
  withVuetify,
  (_) => {
    // loadFonts();
    app.component('SgTitle', SgTitle);
    app.component('SgLabel', SgLabel);
    app.component('SgMap', SgMap);
    app.component('SgButton', SgButton);
    app.component('SgRadio', SgRadio);
    app.component('SgImageViewer', SgImageViewer);
    app.component('SgCheckbox', SgCheckbox);
    return {
      template: `<story />`,
    };
  },
];

**Comment by longzheng** [comment]
In case anyone else runs into this issue, I solved this by making sure my environment variable with defined for the production environment.

I realised that the Storybook dev server uses `.env.development` and Storybook build uses `.env.production` (like a Vite production build).
