### ISSUE TITLE
[Bug] p.exports.jsxDEV is not a function when building / deploying storybook

### ISSUE THREAD

**Issue by Scalahansolo** [storybookjs/builder-vite#497]
### What version of `vite` are you using?

2.9.1

### System info and storybook versions

Environment Info:

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 98.0.1
    Safari: 16.0

### Describe the Bug

I have no issue with running Storybook locally. However whenever I build storybook using `yarn build-storybook` and than try to hit it via `npx http-server ./storybook-static` I end up with the following errors inside of my stories. 

```
TypeError: p.exports.jsxDEV is not a function
    at http://127.0.0.1:8080/assets/config.d4d9dc2c.js:1:5235
    at d (http://127.0.0.1:8080/assets/iframe.6f9367d5.js:1:2575)
    at Generator._invoke (http://127.0.0.1:8080/assets/iframe.6f9367d5.js:1:4557)
    at Generator.next (http://127.0.0.1:8080/assets/iframe.6f9367d5.js:1:3088)
    at S (http://127.0.0.1:8080/assets/config.d4d9dc2c.js:1:2490)
    at i (http://127.0.0.1:8080/assets/config.d4d9dc2c.js:1:2687)
    at http://127.0.0.1:8080/assets/config.d4d9dc2c.js:1:2746
    at new Promise (<anonymous>)
    at t.<anonymous> (http://127.0.0.1:8080/assets/config.d4d9dc2c.js:1:2628)
    at t.g (http://127.0.0.1:8080/assets/config.d4d9dc2c.js:1:5538)    
```

![ScreenShot 09-15 at 09 03](https://user-images.githubusercontent.com/4317253/190438916-71ec6d8e-bcc0-4da4-8fdf-3b07d31f6f63.png)

I've tried to track down this issue in various other issues, but have been unsuccessful so far. It's also probably worth mentioning that I am using `builder-vite` version `0.1.41`.

I would be happy to help track down and solve this issue, just not sure where to start. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Scalahansolo** [comment]
My `.storybook/main.ts` file...

```
const macrosPlugin = require('vite-plugin-babel-macros');
const webfontDownload = require('vite-plugin-webfont-dl');

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    'multiple-themes-stitches',
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-vite',
  },
  async viteFinal(config, { configType }) {
    config.plugins = [...config.plugins, macrosPlugin.default(), webfontDownload.default()];

    return config;
  },
  features: {
    storyStoreV7: true,
    babelModeV7: true,
  },
};
```

Also worth noting here... I just upgraded my codebase / deps to Vite 3+ and the most recent version of `builder-vite`. Issue still occurs.

**Comment by Scalahansolo** [comment]
Ugh... I just removed `'multiple-themes-stitches'` because I was no longer using it... Works fine it seems now. Going to try to actually deploy this story on `chromatic` before closing this issue out.
