### ISSUE TITLE
[Bug] Typescript must be installed when using react

### ISSUE THREAD

**Issue by brupelo** [storybookjs/builder-vite#499]
### What version of `vite` are you using?

3.1.0

### System info and storybook versions

Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 17.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
  npmPackages:
    @storybook/addon-actions: ^6.5.12 => 6.5.12
    @storybook/addon-essentials: ^6.5.12 => 6.5.12
    @storybook/addon-interactions: ^6.5.12 => 6.5.12
    @storybook/addon-links: ^6.5.12 => 6.5.12
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/react: ^6.5.12 => 6.5.12
    @storybook/testing-library: ^0.0.13 => 0.0.13

### Describe the Bug

Below you can see when I've got asked `Do you want to run the 'npm7' migration on your project?` I've answered
no but If I try a new test from scratch and I do answer yeah I'll end up having the same crash.

```
D:\test>nvm ls

    18.9.0
    18.8.0
    18.5.0
  * 17.8.0 (Currently using 64-bit executable)
    16.17.0
    16.10.0
    16.8.0
    14.20.0

D:\test>node --version
v17.8.0

D:\test>npm --version
8.5.5

D:\test>npm create vite@latest                             
√ Project name: ... vite-project                           
√ Select a framework: » React                              
√ Select a variant: » JavaScript                           
                                                           
Scaffolding project in D:\test\vite-project...             
                                                           
Done. Now run:                                             
                                                           
  cd vite-project                                          
  npm install                                              
  npm run dev                                              
                                                           
D:\test>cd vite-project

D:\test\vite-project>npm install

added 87 packages, and audited 88 packages in 14s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

D:\test\vite-project>cat package.json
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@vitejs/plugin-react": "^2.1.0",
    "vite": "^3.1.0"
  }
}                                                           

D:\test\vite-project>npx sb init --builder @storybook/builder-vite && npm run storybook

 storybook init - the simplest way to add a Storybook to your project.

 • Detecting project type. ✓
 • Adding Storybook support to your "React" app

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1520 packages, and audited 1608 packages in 1m

242 packages are looking for funding
  run `npm fund` for details

22 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
. ✓
 • Preparing to install dependencies. ✓



up to date, audited 1608 packages in 3s

242 packages are looking for funding
  run `npm fund` for details

22 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
. ✓
� checking possible migrations..
� found a 'npm7' migration:

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│   We've detected you are running npm 8.5.5                                                │
│   which has peer dependency semantics which Storybook is incompatible with.               │
│                                                                                           │
│   In order to work with Storybook's package structure, you'll need to run `npm` with      │
│   the                                                                                     │
│   `--legacy-peer-deps=true` flag. We can generate an `.npmrc` which will do that          │
│   automatically.                                                                          │
│                                                                                           │
│   More info: https://github.com/storybookjs/storybook/issues/18298                        │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯√ Do you want to run the 'npm7' migration on your project? ... no
Skipping the npm7 migration.

If you change your mind, run 'npx storybook@next automigrate'

✅ migration check successfully ran


To run your Storybook, type:

   npm run storybook

For more information visit: https://storybook.js.org


> vite-project@0.0.0 storybook
> start-storybook -p 6006

info @storybook/react v6.5.12
info
info => Loading presets
ERR! Error: Cannot find module 'typescript'
ERR! Require stack:
ERR! - D:\test\vite-project\node_modules\react-docgen-typescript\lib\parser.js
ERR! - D:\test\vite-project\node_modules\react-docgen-typescript\lib\index.js
ERR! - D:\test\vite-project\node_modules\@joshwooding\vite-plugin-react-docgen-typescript\dist\index.cjs
ERR! - D:\test\vite-project\node_modules\@storybook\builder-vite\dist\vite-config.js
ERR! - D:\test\vite-project\node_modules\@storybook\builder-vite\dist\vite-server.js
ERR! - D:\test\vite-project\node_modules\@storybook\builder-vite\dist\index.js
ERR! - D:\test\vite-project\node_modules\@storybook\core-server\dist\cjs\utils\get-preview-builder.js
ERR! - D:\test\vite-project\node_modules\@storybook\core-server\dist\cjs\build-static.js
ERR! - D:\test\vite-project\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - D:\test\vite-project\node_modules\@storybook\core\dist\cjs\server.js
ERR! - D:\test\vite-project\node_modules\@storybook\core\server.js
ERR! - D:\test\vite-project\node_modules\@storybook\react\dist\cjs\server\index.js
ERR! - D:\test\vite-project\node_modules\@storybook\react\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (D:\test\vite-project\node_modules\react-docgen-typescript\lib\parser.js:26:10)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1099:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!  Error: Cannot find module 'typescript'
ERR! Require stack:
ERR! - D:\test\vite-project\node_modules\react-docgen-typescript\lib\parser.js
ERR! - D:\test\vite-project\node_modules\react-docgen-typescript\lib\index.js
ERR! - D:\test\vite-project\node_modules\@joshwooding\vite-plugin-react-docgen-typescript\dist\index.cjs
ERR! - D:\test\vite-project\node_modules\@storybook\builder-vite\dist\vite-config.js
ERR! - D:\test\vite-project\node_modules\@storybook\builder-vite\dist\vite-server.js
ERR! - D:\test\vite-project\node_modules\@storybook\builder-vite\dist\index.js
ERR! - D:\test\vite-project\node_modules\@storybook\core-server\dist\cjs\utils\get-preview-builder.js
ERR! - D:\test\vite-project\node_modules\@storybook\core-server\dist\cjs\build-static.js
ERR! - D:\test\vite-project\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - D:\test\vite-project\node_modules\@storybook\core\dist\cjs\server.js
ERR! - D:\test\vite-project\node_modules\@storybook\core\server.js
ERR! - D:\test\vite-project\node_modules\@storybook\react\dist\cjs\server\index.js
ERR! - D:\test\vite-project\node_modules\@storybook\react\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (D:\test\vite-project\node_modules\react-docgen-typescript\lib\parser.js:26:10)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1099:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     'D:\\test\\vite-project\\node_modules\\react-docgen-typescript\\lib\\parser.js',
ERR!     'D:\\test\\vite-project\\node_modules\\react-docgen-typescript\\lib\\index.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@joshwooding\\vite-plugin-react-docgen-typescript\\dist\\index.cjs',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\builder-vite\\dist\\vite-config.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\builder-vite\\dist\\vite-server.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\builder-vite\\dist\\index.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\core-server\\dist\\cjs\\utils\\get-preview-builder.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\core-server\\dist\\cjs\\build-static.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\core-server\\dist\\cjs\\index.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\core\\dist\\cjs\\server.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\core\\server.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\react\\dist\\cjs\\server\\index.js',
ERR!     'D:\\test\\vite-project\\node_modules\\@storybook\\react\\bin\\index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
? Would you like to send crash reports to Storybook? » (Y/n)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
@joshwooding any thoughts on how we can avoid problems for projects without typescript?

**Comment by joshwooding** [comment]
Hi @brupelo, can you try to reproduce this with [0.2.4](https://github.com/storybookjs/builder-vite/releases/tag/v0.2.4) please

**Comment by joshwooding** [comment]
Closing for now since there hasn't been any activity.

**Comment by brupelo** [comment]
@IanVS , @joshwooding  Hi guys, first of all thanks for taking a look to this one and sorry for the delay answering. Today I've allocated some time and I gave it a shot to the latest 0.2.5 version from scratch. Pasting couple of sessions that ended up without being able to bootstrap (following the start guide again, I didn't do anything fancier).

<details>
  <summary>Attempt1 (npm migration: no): vite-project3</summary>
  
```
D:\test>npm create vite@latest                                                                 
√ Project name: ... vite-project3                                                              
√ Select a framework: » React                                                                  
√ Select a variant: » JavaScript                                                               
                                                                                               
Scaffolding project in D:\test\vite-project3...                                                
                                                                                               
Done. Now run:                                                                                 
                                                                                               
  cd vite-project3                                                                             
  npm install                                                                                  
  npm run dev                                                                                  
                                                                                               
                                                                                               
D:\test>cd vite-project3                                                                       
                                                                                               
D:\test\vite-project3>npm install                                                              
                                                                                               
added 85 packages, and audited 86 packages in 14s                                              
                                                                                               
8 packages are looking for funding                                                             
  run `npm fund` for details                                                                   
                                                                                               
found 0 vulnerabilities                                                                        
                                                                                               
D:\test\vite-project3>npx sb init --builder @storybook/builder-vite                            
                                                                                               
 storybook init - the simplest way to add a Storybook to your project.                         
                                                                                               
 • Detecting project type. ✓                                                                   
 • Adding Storybook support to your "React" app                                                
                                                                                               
attention => Storybook now collects completely anonymous telemetry regarding usage.            
This information is used to shape Storybook's roadmap and prioritize features.                 
You can learn more, including how to opt-out if you'd not like to participate in this anonymous
 program, by visiting the following URL:                                                       
https://storybook.js.org/telemetry                                                             
                                                                                               
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs   
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecat
ed                                                                                             
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, s
o this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility           
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated           
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#
deprecated                                                                                     
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Up
grade to chokidar 3 with 15x fewer dependencies                                                
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated        
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dr
opped, and newer ECMAScript syntax/features added                                              
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code shoul
d use the URLSearchParams API instead.                                                         
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use
 Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/
blog/math-random for details.                                                                  
                                                                                               
added 1527 packages, and audited 1613 packages in 2m                                           
                                                                                               
252 packages are looking for funding                                                           
  run `npm fund` for details                                                                   
                                                                                               
22 high severity vulnerabilities                                                               
                                                                                               
To address issues that do not require attention, run:                                          
  npm audit fix                                                                                
                                                                                               
To address all issues (including breaking changes), run:                                       
  npm audit fix --force                                                                        
                                                                                               
Run `npm audit` for details.                                                                   
. ✓                                                                                            
 • Preparing to install dependencies. ✓                                                        
                                                                                               
                                                                                               
                                                                                               
up to date, audited 1613 packages in 3s                                                        
                                                                                               
252 packages are looking for funding                                                           
  run `npm fund` for details                                                                   
                                                                                               
22 high severity vulnerabilities                                                               
                                                                                               
To address issues that do not require attention, run:                                          
  npm audit fix                                                                                
                                                                                               
To address all issues (including breaking changes), run:                                       
  npm audit fix --force                                                                        
                                                                                               
Run `npm audit` for details.                                                                   
. ✓                                                                                            
� checking possible migrations..                                                               
� found a 'npm7' migration:                                                                    
                                                                                               
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│   We've detected you are running npm 8.5.5                                                  │
│   which has peer dependency semantics which Storybook is incompatible with.                 │
│                                                                                             │
│   In order to work with Storybook's package structure, you'll need to run `npm` with the    │
│   `--legacy-peer-deps=true` flag. We can generate an `.npmrc` which will do that            │
│   automatically.                                                                            │
│                                                                                             │
│   More info: https://github.com/storybookjs/storybook/issues/18298                          │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
√ Do you want to run the 'npm7' migration on your project? ... no                              
Skipping the npm7 migration.                                                                   
                                                                                               
If you change your mind, run 'npx storybook@next automigrate'                                  
                                                                                               
✅ migration check successfully ran                                                             
                                                                                               
                                                                                               
To run your Storybook, type:                                                                   
                                                                                               
   npm run storybook                                                                           
                                                                                               
For more information visit: https://storybook.js.org                                           
                                                                                               
                                                                                               
D:\test\vite-project3>npm run storybook                                                        
                                                                                               
> vite-project3@0.0.0 storybook                                                                
> start-storybook -p 6006                                                                      
                                                                                               
info @storybook/react v6.5.13                                                                  
info                                                                                           
info => Loading presets                                                                        
                                                                                               
info => Ignoring cached manager due to change in manager config                                
i ｢wdm｣: wait until bundle finished:                                                           
node:internal/crypto/hash:67                                                                   
  this[kHandle] = new _Hash(algorithm, xofLen);                                                
                  ^                                                                            
                                                                                               
Error: error:0308010C:digital envelope routines::unsupported                                   
    at new Hash (node:internal/crypto/hash:67:19)                                              
    at Object.createHash (node:crypto:135:10)                                                  
    at module.exports (D:\test\vite-project3\node_modules\webpack\lib\util\createHash.js:135:53
)                                                                                              
    at NormalModule._initBuildHash (D:\test\vite-project3\node_modules\webpack\lib\NormalModule
.js:417:16)                                                                                    
    at handleParseError (D:\test\vite-project3\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\test\vite-project3\node_modules\webpack\lib\NormalModule.js:503:5                    
    at D:\test\vite-project3\node_modules\webpack\lib\NormalModule.js:358:12                   
    at D:\test\vite-project3\node_modules\loader-runner\lib\LoaderRunner.js:373:3              
    at iterateNormalLoaders (D:\test\vite-project3\node_modules\loader-runner\lib\LoaderRunner.
js:214:10)                                                                                     
    at Array.<anonymous> (D:\test\vite-project3\node_modules\loader-runner\lib\LoaderRunner.js:
205:4) {                                                                                       
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],     
  library: 'digital envelope routines',                                                        
  reason: 'unsupported',                                                                       
  code: 'ERR_OSSL_EVP_UNSUPPORTED'                                                             
}                                                                                              
                                                                                               
Node.js v17.8.0                                                                                
                                                                                               
D:\test\vite-project3>node --version                                                           
v17.8.0                                                                                        
                                                                                               
D:\test\vite-project3>npm --version                                                            
8.5.5                                                                                          
                                                                                               
D:\test\vite-project3>npm ls                                                                   
vite-project3@0.0.0 D:\test\vite-project3                                                      
+-- @babel/core@7.20.2                                                                         
+-- @storybook/addon-actions@6.5.13                                                            
+-- @storybook/addon-essentials@6.5.13                                                         
+-- @storybook/addon-interactions@6.5.13                                                       
+-- @storybook/addon-links@6.5.13                                                              
+-- @storybook/builder-vite@0.2.5                                                              
+-- @storybook/react@6.5.13                                                                    
+-- @storybook/testing-library@0.0.13                                                          
+-- @types/react-dom@18.0.9                                                                    
+-- @types/react@18.0.25                                                                       
+-- @vitejs/plugin-react@2.2.0                                                                 
+-- babel-loader@8.3.0                                                                         
+-- react-dom@18.2.0                                                                           
+-- react@18.2.0                                                                               
`-- vite@3.2.4                                                                                 
                                                                                               


```

</details>

<details>
<summary>Attempt2 (npm migration: yes): vite-project4</summary>

```
D:\test>npm create vite@latest
√ Project name: ... vite-project4
√ Select a framework: » React
√ Select a variant: » JavaScript

Scaffolding project in D:\test\vite-project4...

Done. Now run:

  cd vite-project4
  npm install
  npm run dev


D:\test>cd vite-project4

D:\test\vite-project4>npm install

added 85 packages, and audited 86 packages in 9s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

D:\test\vite-project4>npx sb init --builder @storybook/builder-vite

 storybook init - the simplest way to add a Storybook to your project.

 • Detecting project type. ✓
 • Adding Storybook support to your "React" app

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1527 packages, and audited 1613 packages in 2m

252 packages are looking for funding
  run `npm fund` for details

22 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
. ✓
 • Preparing to install dependencies. ✓



up to date, audited 1613 packages in 3s

252 packages are looking for funding
  run `npm fund` for details

22 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
. ✓
� checking possible migrations..
� found a 'npm7' migration:

╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│   We've detected you are running npm 8.5.5                                                  │
│   which has peer dependency semantics which Storybook is incompatible with.                 │
│                                                                                             │
│   In order to work with Storybook's package structure, you'll need to run `npm` with the    │
│   `--legacy-peer-deps=true` flag. We can generate an `.npmrc` which will do that            │
│   automatically.                                                                            │
│                                                                                             │
│   More info: https://github.com/storybookjs/storybook/issues/18298                          │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯√ Do you want to run the 'npm7' migration on your project? ... yes
✅ ran npm7 migration

✅ migration check successfully ran


To run your Storybook, type:

   npm run storybook

For more information visit: https://storybook.js.org


D:\test\vite-project4>npm run storybook

> vite-project4@0.0.0 storybook
> start-storybook -p 6006

info @storybook/react v6.5.13
info
info => Loading presets

info => Ignoring cached manager due to change in manager config
i ｢wdm｣: wait until bundle finished:
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (D:\test\vite-project4\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\test\vite-project4\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\test\vite-project4\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\test\vite-project4\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\test\vite-project4\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\test\vite-project4\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\test\vite-project4\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\test\vite-project4\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.8.0

```
</details>

If you want me to try again pls let me know exactly which nodejs + npm versions should I try. Thanks!

**Comment by joshwooding** [comment]
@brupelo Thanks for the update. V17 of node introduced some deprecations for openssl which is what is causing those `digital envelope routines::unsupported` messages. You should be able to fix this using the `--openssl-legacy-provider` option for node https://nodejs.org/api/cli.html#--openssl-legacy-provider

You might need to control this via env variables e.g. `export NODE_OPTIONS=--openssl-legacy-provider`
