### ISSUE TITLE
[Bug] Incopatibility with storybook-addon-next

### ISSUE THREAD

**Issue by dvakatsiienko** [storybookjs/builder-vite#501]
### What version of `vite` are you using?

vite

### System info and storybook versions

System:
 OS: MacOS BigSur 11.7
 CPU: 2.3 GHz Quad-Core Intel Core i7
Binaries:
 Node: 16.16.0
 yarn: 1.22.15
Browsers:
 Chrome: 105.0.5195.125
npmPackages:
    "@storybook/addon-actions": "6.5.12",
    "@storybook/addon-essentials": "6.5.12",
    "@storybook/addon-links": "6.5.12",
    "@storybook/builder-vite": "0.2.2",
    "@storybook/react": "6.5.12",
    "storybook-addon-next": "1.6.9",

### Describe the Bug

Using **[storybook-addon-next](https://github.com/RyanClementsHax/storybook-addon-next)** in combination with **[builder-vite](https://github.com/storybookjs/builder-vite)** produces an error once storybook server started.

[Reproduce repo link](https://github.com/dvakatsiienko/next-vite-storybook).
I've added instruction to start.

**A warning message**:
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: 
```

**Error message is somehow related with `next-image-stub.js`**:
```
Uncaught TypeError: Invalid Version: undefined
    at new SemVer (semver.js:19:13)
    at compare (compare.js:3:3)
    at Object.gt (gt.js:2:29)
    at node_modules/storybook-addon-next/dist/images/next-image-stub.js (next-image-stub.js:7:22)
    at __require2 (chunk-S5KM4IGW.js?v=7ad206d8:18:50)
    at node_modules/storybook-addon-next/dist/preview.js (preview.js:7:1)
    at __require2 (chunk-S5KM4IGW.js?v=7ad206d8:18:50)
    at dep:storybook-addon-next_dist_preview__js:1:16
```

#### Steps to reproduce
- Clone repository
- yarn
- yarn storybook:start
- Once Vite bundled, go to http://localhost:6006/
- Inspect an error in console

#### Video

https://user-images.githubusercontent.com/15727958/192000642-f0bffba6-b551-4f5f-aaac-5830ac4ff5ad.mp4

### Link to Minimal Reproducible Example

https://github.com/dvakatsiienko/next-vite-storybook

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by joshwooding** [comment]
@dvakatsiienko Hi, your reproduction repo is private. Do you mind giving us access?

**Comment by joshwooding** [comment]
Saying that I do think I know what the issue is. storybook-addon-next was only create to support webpack. The issue here is because __NEXT_VERSION isn't set. Normally this is done using the define plugin https://github.com/RyanClementsHax/storybook-addon-next/blob/fb4ade3be790f68cf3eb47cff53eb45bd5d945d4/src/utils.ts#L8 so maybe if you re-create that using vite's define option it might work but hard to say.

**Comment by dvakatsiienko** [comment]
I've though it's dead so deleted repository with repro example.
Got it back, [check here](https://github.com/dvakatsiienko/next-vite-storybook-bug-reproduction).

**Comment by dvakatsiienko** [comment]
@joshwooding I'll take a look

> Saying that I do think I know what the issue is. storybook-addon-next was only created to support webpack. The issue here is because __NEXT_VERSION isn't set. Normally this is done using the define plugin [RyanClementsHax/storybook-addon-next@`fb4ade3`/src/utils.ts#L8](https://github.com/RyanClementsHax/storybook-addon-next/blob/fb4ade3be790f68cf3eb47cff53eb45bd5d945d4/src/utils.ts#L8) so maybe if you re-create that using vite's define option it might work but hard to say.

**Comment by dvakatsiienko** [comment]
I've created an issue for [storybook-addon-next](https://github.com/RyanClementsHax/storybook-addon-next) as well, RyanClementsHax/storybook-addon-next#120.
@RyanClementsHax gave his comment from his side why it won't work for now, so let's wait I guess.

**Comment by sneko** [comment]
@dvakatsiienko did you find a workaround? I had so many issues using webpack+storybook+sass... that I'm sceptical to go back to it :/

**Comment by dvakatsiienko** [comment]
@sneko No, I've left the adaptation entirely due to no need. Take a look, maybe they did the solutions during last month or two.

**Comment by sneko** [comment]
At the end I made a storybook project from scratch and patched mine... it seems due to specific dependencies versions addind Sass was messing up (really messing up), but now it's good. So bye bye Vite, going to Webpack even if it feels a bit slower ^^

Thanks for answering ;)

**Comment by IanVS** [comment]
Next.js isn't officially supported by the storybook vite builder, for the reasons mentioned above.  I think you're best off sticking with the webpack builder when using next.js, to avoid different behaviors between your storybook and app.

If you'd like to speed things up a bit, you can try out storybook 7.0, which should be a good deal faster, even when using Webpack.

**Comment by jakubzet** [comment]
Hi! Just found this issue, as I'm also trying to kick up the Storybbok 7 with Vite and Next plugin together (I have issues with running Webpack version, but that's another story...). 

So, indeed using "define" option in Vite config, as described by @joshwooding above works :) It's similar to one below - for now I've just hard-coded the Next version, but I'll just copy-and-adjust code fragment from storybook-addon-next used to fetch the NextJs version from it's package.json file.

```
  async viteFinal(config) {
    return mergeConfig(config, {
      define: {
        "process.env": {
          __NEXT_VERSION: "13.1.1",
        },
      },
    });
  },
```
