### ISSUE TITLE
[Bug] Build doesn't work with Github pages

### ISSUE THREAD

**Issue by morewings** [storybookjs/builder-vite#514]
### What version of `vite` are you using?

3.1.0

### System info and storybook versions

Environment Info:

  System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Edge: 90.0.818.42
    Firefox: 105.0.2
    Safari: 16.0

"@storybook/addon-actions": "^6.5.12",
    "@storybook/addon-essentials": "^6.5.12",
    "@storybook/addon-links": "^6.5.12",
    "@storybook/builder-vite": "^0.2.4",
    "@storybook/react": "^6.5.12",
    "@storybook/testing-library": "^0.0.13",

### Describe the Bug

I have storybook build deployed to Github pages - https://morewings.github.io/forge/

Stories give me bunch of errors. 

```
browser-polyfill.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1:7229
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (browser-polyfill.js:1:6912)
    at Object.apply (browser-polyfill.js:1:6341)
    at S (content.bundle.js:1:20114)
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
browser-polyfill.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1:7229
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (browser-polyfill.js:1:6912)
    at Object.apply (browser-polyfill.js:1:6341)
    at S (content.bundle.js:1:20114)
/assets/iframe.75cdf45e.js:1          Failed to load resource: the server responded with a status of 404 ()
browser-polyfill.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1:7229
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (browser-polyfill.js:1:6912)
    at Object.apply (browser-polyfill.js:1:6341)
    at S (content.bundle.js:1:20114)
/favicon.ico:1          Failed to load resource: the server responded with a status of 404 ()
browser-polyfill.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1:7229
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (browser-polyfill.js:1:6912)
    at Object.apply (browser-polyfill.js:1:6341)
    at S (content.bundle.js:1:20114)
browser-polyfill.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1:7229
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (browser-polyfill.js:1:6912)
    at Object.apply (browser-polyfill.js:1:6341)
    at S (content.bundle.js:1:20114)
browser-polyfill.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at browser-polyfill.js:1:7229
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (browser-polyfill.js:1:6912)
    at Object.apply (browser-polyfill.js:1:6341)
    at S (content.bundle.js:1:20114)

```

Development mode works ok.

### Link to Minimal Reproducible Example

https://github.com/morewings/forge/tree/master/packages/library-vite

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by morewings** [comment]
I found the answer myself. `base: '/<Repo Name>/'` has to be added to `.storybook/main.js`

**Comment by morewings** [comment]
Thanks
