### ISSUE TITLE
[Bug] Storybook fails to run after react-docgen alpha version update

### ISSUE THREAD

**Issue by igorxciv** [storybookjs/builder-vite#530]
### What version of `vite` are you using?

4.0.1

### System info and storybook versions

System:
    OS: macOS 13.0.1
Binaries:
    Node.js: v16.18.1
    Yarn: 1.22.19
npmPackages:
    "@babel/core": "7.20.5",
    "@storybook/addon-actions": "6.5.14",
    "@storybook/addon-essentials": "6.5.14",
    "@storybook/addon-interactions": "6.5.14",
    "@storybook/addon-links": "6.5.14",
    "@storybook/builder-vite": "0.2.5",
    "@storybook/react": "6.5.14",
    "@vitejs/plugin-react": "3.0.0",
    "babel-loader": "9.1.0",
    "typescript": "4.9.4",
    "vite": "4.0.1",
    "vite-plugin-dts": "1.7.1"

### Describe the Bug

Using the storybook with Vite React project after `yarn create vite`

But when I run storybook, I get the following error:
```
⋊> ~/w/project ◦ yarn storybook                                                                                                     
yarn run v1.22.19
$ start-storybook -p 6006
info @storybook/react v6.5.14
info
info => Loading presets
ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/igor/workspace/project/node_modules/react-docgen/dist/main.js from /Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js not supported.
ERR! Instead change the require of main.js in /Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js:8:24)
ERR!     at /Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-config.js:236:85
ERR!     at async pluginConfig (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-config.js:236:37)
ERR!     at async commonConfig (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-config.js:66:18)
ERR!     at async createViteServer (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-server.js:10:24)
ERR!     at async Object.start (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/index.js:64:14)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/igor/workspace/project/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/Users/igor/workspace/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/igor/workspace/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/igor/workspace/project/node_modules/react-docgen/dist/main.js from /Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js not supported.
ERR! Instead change the require of main.js in /Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js:8:24)
ERR!     at /Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-config.js:236:85
ERR!     at async pluginConfig (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-config.js:236:37)
ERR!     at async commonConfig (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-config.js:66:18)
ERR!     at async createViteServer (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/vite-server.js:10:24)
ERR!     at async Object.start (/Users/igor/workspace/project/node_modules/@storybook/builder-vite/dist/index.js:64:14)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/igor/workspace/project/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/Users/igor/workspace/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/igor/workspace/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5) {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }
```

Looks like it started happening after `react-docgen` dependency update from `6.0.0-alpha.3` -> to `6.0.0-alpha.4`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by igorxciv** [comment]
Updating `react-docgen` in `yarn.lock` back to `6.0.0-alpha.3` fixes the problem, but doesn't solve this issue:

yarn.lock:
```
....
react-docgen@^6.0.0-alpha.0:
  version "6.0.0-alpha.3"
  resolved "https://registry.yarnpkg.com/react-docgen/-/react-docgen-6.0.0-alpha.3.tgz#4d8a4916b45de4aadb90eb5f3a6f923edf447928"
  integrity sha512-DDLvB5EV9As1/zoUsct6Iz2Cupw9FObEGD3DMcIs3EDFIoSKyz8FZtoWj3Wj+oodrU4/NfidN0BL5yrapIcTSA==
  dependencies:
    "@babel/core" "^7.7.5"
    "@babel/generator" "^7.12.11"
    ast-types "^0.14.2"
    commander "^2.19.0"
    doctrine "^3.0.0"
    estree-to-babel "^3.1.0"
    neo-async "^2.6.1"
    node-dir "^0.1.10"
    resolve "^1.17.0"
    strip-indent "^3.0.0"
....
```

**Comment by entomb** [comment]
had the same issue, used the same solution but with npm:

```
  "dependencies": {
  
  ...
  
    "react-docgen": "6.0.0-alpha.3"
  },
  "overrides": {
    "@storybook/builder-vite": {
      "react-docgen": "$react-docgen"
    }
  }

```

**Comment by IanVS** [comment]
Thanks, looks like It's now ESM only.  Pinning to the earlier versions should be fine for now, until we can find another way to deal with this.  I really wish packages wouldn't do this.  :(
