### ISSUE TITLE
[Bug] [vite] Internal server error: No ESLint configuration found in /virtual:/@storybook/builder-vite.

### ISSUE THREAD

**Issue by con-dog** [storybookjs/builder-vite#572]
### What version of `vite` are you using?

4.2.0

### System info and storybook versions

Environment Info:

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Firefox: 111.0.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.2 => 7.0.2 
    @storybook/addon-interactions: ^7.0.2 => 7.0.2 
    @storybook/addon-links: ^7.0.2 => 7.0.2 
    @storybook/blocks: ^7.0.2 => 7.0.2 
    @storybook/svelte: ^7.0.2 => 7.0.2 
    @storybook/svelte-vite: ^7.0.2 => 7.0.2 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 

### Describe the Bug

Vite + Svelte + TypeScript + ESLint + Storybook

```
// vite.config.ts
import { defineConfig } from 'vite'
import eslint from 'vite-plugin-eslint'
import { svelte } from '@sveltejs/vite-plugin-svelte'

export default defineConfig({
  plugins: [eslint({"exclude": ['**/node_modules/**', '/virtual/**']}), svelte()]
})
```

The error that occurs after running `npm run storybook` : 
```
8:28:42 pm [vite] Internal server error: No ESLint configuration found in /virtual:/@storybook/builder-vite.
  Plugin: vite-plugin-eslint
  File: /virtual:/@storybook/builder-vite/vite-app.js
      at CascadingConfigArrayFactory._finalizeConfigArray (/home/connor/Projects/devemu/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:521:19)
      at CascadingConfigArrayFactory.getConfigArrayForFile (/home/connor/Projects/devemu/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:312:21)
      at CLIEngine.isPathIgnored (/home/connor/Projects/devemu/node_modules/eslint/lib/cli-engine/cli-engine.js:989:18)
      at ESLint.isPathIgnored (/home/connor/Projects/devemu/node_modules/eslint/lib/eslint/eslint.js:681:26)
      at TransformContext.transform (file:///home/connor/Projects/devemu/node_modules/vite-plugin-eslint/dist/index.mjs:1:1868)
      at Object.transform (file:///home/connor/Projects/devemu/node_modules/vite/dist/node/chunks/dep-79892de8.js:43387:44)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///home/connor/Projects/devemu/node_modules/vite/dist/node/chunks/dep-79892de8.js:41105:29)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
There is a PR in the plugin that would fix this, I believe: https://github.com/gxmari007/vite-plugin-eslint/pull/52
